services:
  - type: web
    name: spare-forge-spares
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn spare_forge_spares:app
    autoDeploy: true
